### ISSUE TITLE
Fatal Error - Concurrent map read/write

### ISSUE THREAD

**Issue by gummybera** [berachain/beacon-kit#2057] opened 2024-10-09 14:41 UTC
Reported by a validator - concurrent read/write in go routine causing the process to terminate. Logs attached.

`v0.2.0-alpha.8`, node resumed normal operation on restart.

```
fatal error: concurrent map iteration and map write
goroutine 4473 [running]:
net/http.Header.Clone(...)
        net/http/header.go:106
net/http.cloneOrMakeHeader(0xc0020176e0)
        net/http/clone.go:116 +0x14c
net/http.(*Client).makeHeadersCopier(0x3e5c780, 0xc011872640)
        net/http/client.go:751 +0x33
net/http.(*Client).do(0x3e5c780, 0xc011872640)
        net/http/client.go:612 +0x246
net/http.(*Client).Do(...)
        net/http/client.go:590
--
github.com/berachain/beacon-kit/mod/geth-primitives/pkg/deposit.(*BeaconDepositContractFilterer).FilterDeposit(0xc002180268, 0x291ce00?)
        github.com/berachain/beacon-kit/mod/geth-primitives/pkg/deposit/contract.abigen.go:589 +0x36
github.com/berachain/beacon-kit/mod/execution/pkg/deposit.(*WrappedBeaconDepositContract[...]).ReadDeposits(0x291d000, {0x291d360, 0xc00011c370}, 0x50d950)
        github.com/berachain/beacon-kit/mod/execution/pkg/deposit/contract.go:81 +0xaf
github.com/berachain/beacon-kit/mod/execution/pkg/deposit.(*Service[...]).fetchAndStoreDeposits(0x2937ea0, {0x291d360?, 0xc00011c370?}, 0x50d950?)
        github.com/berachain/beacon-kit/mod/execution/pkg/deposit/sync.go:75 +0x49
github.com/berachain/beacon-kit/mod/execution/pkg/deposit.(*Service[...]).depositFetcher(0x2937ea0, {0x291d360, 0xc00011c370}, {0x2920ba0, 0xc009c57c00?})
        github.com/berachain/beacon-kit/mod/execution/pkg/deposit/sync.go:40 +0x8e
github.com/berachain/beacon-kit/mod/execution/pkg/deposit.(*Service[...]).eventLoop(0x2937ea0, {0x291d360, 0xc00011c370})
        github.com/berachain/beacon-kit/mod/execution/pkg/deposit/service.go:124 +0x65
created by github.com/berachain/beacon-kit/mod/execution/pkg/deposit.(*Service[...]).Start in goroutine 1
        github.com/berachain/beacon-kit/mod/execution/pkg/deposit/service.go:107 +0x18e
```
[log.txt](https://github.com/user-attachments/files/17310050/log.txt)

**Comment by abi87** [comment] 2024-10-10 07:43
Hello @gummybera, I believe https://github.com/berachain/beacon-kit/pull/2058 fixes the issue. Could the validator you mention patch its binary and let us know if the issue is still there?

**Comment by gummybera** [comment] 2024-10-10 14:24
Thanks for the quick turnaround @abi87 ! They haven't faced the problem again since restart, given that its a rare occurence  testing is not going to be simple. If its alright with you we can close this issue for now. Are there any other similar scenarios that we need to watch out for?

**Comment by abi87** [comment] 2024-10-10 14:34
We're reviewing the code in depth and found another concurrency issue, if this is what you are asking.
Again unlikely to occur, but we do have a proposed solution for it https://github.com/berachain/beacon-kit/pull/2060.
Noting here just FYI.
Fine with me closing the issue. Should any crash happen again, please file another issue and I'll triage whether it's an instance of the same issue or a different one.

**Closed by abi87** 2024-10-10 14:34 UTC
