### ISSUE TITLE
CONSENSUS FAILURE with v0.3.0-alpha.0

### ISSUE THREAD

**Issue by joeAtKysenpool** [berachain/beacon-kit#2167] opened 2024-11-20 22:31 UTC
encounter the following when running `v0.3.0-alpha.0`, after upgraded to `v0.4.0-alpha.0` the node recovered by itself.

```
Nov 20 19:01:17 [27765]: 2024-11-20T19:01:17Z WARN Suggested fee recipient is not configured 🔆 service=engine.client fee-recipent=0x0000000000000000000000000000000000000000
Nov 20 19:01:17 [27765]: 2024-11-20T19:01:17Z INFO Forkchoice updated service=execution-engine head_block_hash=0xad5321d76906cf5389926f427ed7fb2d6a64c6ade83b0bc2730a0d6ff2dea8b3 safe_block_hash=0xbb65326f8dea87665206b29e713b548a512a7b63ee5983403cd>
Nov 20 19:01:18 [27765]: 2024-11-20T19:01:18Z INFO Finalizing commit of block module=consensus height=49398 hash=802EE07659141572A6D7548FB68BB5ABA8D944B3ED7D156F22F51D83055BB6E2 root=1BFC1E295AD66ABA2507DD3CF5F33D00D43ADBB49F1899C54429C49B8956E077>
Nov 20 19:01:18 [27765]: 2024-11-20T19:01:18Z INFO processExecutionPayload service=state-processor consensus height=49398 payload height=46549 payload timestamp=1732129277 bound timestamp=1732129277 skip payload verification=false
Nov 20 19:01:18 [27765]: 2024-11-20T19:01:18Z ERRR Failed to process verified beacon block service=blockchain error=payload timestamp, max: 1732129277, got: 1732129277: timestamp too far in the future
Nov 20 19:01:18 [27765]: 2024-11-20T19:01:18Z ERRR Error in proxyAppConn.FinalizeBlock module=state err=payload timestamp, max: 1732129277, got: 1732129277: timestamp too far in the future
Nov 20 19:01:18 [27765]: 2024-11-20T19:01:18Z ERRR CONSENSUS FAILURE!!! module=consensus err=failed to apply block; error payload timestamp, max: 1732129277, got: 1732129277: timestamp too far in the future
Nov 20 19:01:18 [27765]: goroutine 4684 [running]:
Nov 20 19:01:18 [27765]: runtime/debug.Stack()
Nov 20 19:01:18 [27765]:         runtime/debug/stack.go:26 +0x5e
Nov 20 19:01:18 [27765]: github.com/cometbft/cometbft/internal/consensus.(*State).receiveRoutine.func2()
Nov 20 19:01:18 [27765]:         github.com/cometbft/cometbft@v1.0.0-rc1.0.20240806094948-2c4293ef36c4/internal/consensus/state.go:805 +0x46
Nov 20 19:01:18 [27765]: panic({0x1f0aa80?, 0xc007b2d380?})
Nov 20 19:01:18 [27765]:         runtime/panic.go:785 +0x132
Nov 20 19:01:18 [27765]: github.com/cometbft/cometbft/internal/consensus.(*State).finalizeCommit(0xc000d46408, 0xc0f6)
Nov 20 19:01:18 [27765]:         github.com/cometbft/cometbft@v1.0.0-rc1.0.20240806094948-2c4293ef36c4/internal/consensus/state.go:1925 +0xd25
Nov 20 19:01:18 [27765]: github.com/cometbft/cometbft/internal/consensus.(*State).tryFinalizeCommit(0xc000d46408, 0xc0f6)
Nov 20 19:01:18 [27765]:         github.com/cometbft/cometbft@v1.0.0-rc1.0.20240806094948-2c4293ef36c4/internal/consensus/state.go:1825 +0x349
Nov 20 19:01:18 [27765]: github.com/cometbft/cometbft/internal/consensus.(*State).enterCommit.func1()
Nov 20 19:01:18 [27765]:         github.com/cometbft/cometbft@v1.0.0-rc1.0.20240806094948-2c4293ef36c4/internal/consensus/state.go:1760 +0x9c
Nov 20 19:01:18 [27765]: github.com/cometbft/cometbft/internal/consensus.(*State).enterCommit(0xc000d46408, 0xc0f6, 0x0)
Nov 20 19:01:18 [27765]:         github.com/cometbft/cometbft@v1.0.0-rc1.0.20240806094948-2c4293ef36c4/internal/consensus/state.go:1798 +0xc9b
Nov 20 19:01:18 [27765]: github.com/cometbft/cometbft/internal/consensus.(*State).addVote(0xc000d46408, 0xc00505ef70, {0xc0027127e0, 0x28})
Nov 20 19:01:18 [27765]:         github.com/cometbft/cometbft@v1.0.0-rc1.0.20240806094948-2c4293ef36c4/internal/consensus/state.go:2485 +0x1b45
Nov 20 19:01:18 [27765]: github.com/cometbft/cometbft/internal/consensus.(*State).tryAddVote(0xc000d46408, 0xc00505ef70, {0xc0027127e0?, 0x0?})
Nov 20 19:01:18 [27765]:         github.com/cometbft/cometbft@v1.0.0-rc1.0.20240806094948-2c4293ef36c4/internal/consensus/state.go:2239 +0x26
Nov 20 19:01:18 [27765]: github.com/cometbft/cometbft/internal/consensus.(*State).handleMsg(0xc000d46408, {{0x2830500, 0xc003de4e58}, {0xc0027127e0, 0x28}, {0x0, 0x0, 0x0}})
Nov 20 19:01:18 [27765]:         github.com/cometbft/cometbft@v1.0.0-rc1.0.20240806094948-2c4293ef36c4/internal/consensus/state.go:933 +0x425
Nov 20 19:01:18 [27765]: github.com/cometbft/cometbft/internal/consensus.(*State).receiveRoutine(0xc000d46408, 0x0)
Nov 20 19:01:18 [27765]:         github.com/cometbft/cometbft@v1.0.0-rc1.0.20240806094948-2c4293ef36c4/internal/consensus/state.go:840 +0x409
Nov 20 19:01:18 [27765]: created by github.com/cometbft/cometbft/internal/consensus.(*State).OnStart in goroutine 4602
Nov 20 19:01:18 [27765]:         github.com/cometbft/cometbft@v1.0.0-rc1.0.20240806094948-2c4293ef36c4/internal/consensus/state.go:402 +0x107
Nov 20 19:01:18 [27765]: 2024-11-20T19:01:18Z INFO Stopping baseWAL service module=consensus wal=/home/ubuntu/.beacond/data/cs.wal/wal impl=baseWAL
Nov 20 19:01:18 [27765]: 2024-11-20T19:01:18Z INFO Stopping Group service module=consensus wal=/home/ubuntu/.beacond/data/cs.wal/wal impl=Group
Nov 20 19:01:18 [27765]: 2024-11-20T19:01:18Z INFO Timed out module=consensus dur=1000 height=49398 round=0 step=RoundStepPrevoteWait
```

**Comment by abi87** [comment] 2024-11-20 22:42
Thanks @joeAtKysenpool for filing the issue.
Based on the logs, here is my explanation for the panic:
- Panic happens around upgrade of Boonet from v0.3.0-alpha.0 to v.0.4.0-alpha.0
- Panic is due to the fact that a block is finalizing, meaning that a super majority of nodes approved it, but the block is still invalid for your node
- I suspect this happened because v.0.4.0-alpha.0 changes the timestamp validations wrt 0.3.0-alpha.0 binary without proper backward compatible. So probably:
  - A super majority of validators upgraded and started immediately to work with the new rules
  - Your node upgraded was slightly later than others, so your node saw as confirmed a block invalid with the previous rules
In such a case consensus correctly panics (this is validated consensus, so no majority can convince your node that an invalid thing it is valid; it can only drive preference towards one of the valid alternatives)

It should be all good now, as validator upgrade and now everyone is using the same rule
BUT in retrospect we should have activate the change in timestamp rules at the same height as the minting.
Please keep monitoring and let us know whether this issue happens again

**Comment by abi87** [comment] 2024-11-22 09:05
Looks like panic didn't show up again and we confirmed the explaination internally. Closing this down

**Closed by abi87** 2024-11-22 09:05 UTC
